
export type ToolStatus = "ready" | "coming";

export type ToolCategory = 
  | "organize" 
  | "convert" 
  | "edit" 
  | "security" 
  | "optimize" 
  | "pptx"
  | "ai"
  | "extract";

export type AcceptedFileType = 
  | ".pdf" 
  | ".pptx" 
  | ".docx" 
  | ".doc" 
  | ".xlsx" 
  | ".xls" 
  | ".jpg" 
  | ".jpeg" 
  | ".png" 
  | ".gif" 
  | ".bmp" 
  | ".webp"
  | ".tiff"
  | ".tif";

export interface ToolConfig {
  endpoint: string;
  method: "POST" | "GET";
  acceptedFiles: AcceptedFileType[];
  multiFile: boolean;
  minFiles?: number;
  formFields?: FormFieldConfig[];
  outputFileName: string;
  outputMimeType: string;
}

export interface FormFieldConfig {
  name: string;
  label: string;
  type: "text" | "number" | "select" | "checkbox" | "range";
  defaultValue: string | number | boolean;
  options?: { value: string; label: string }[];
  min?: number;
  max?: number;
  step?: number;
  placeholder?: string;
  required?: boolean;
  /**
   * For tools that have an "operation" select (like the Image Editor),
   * this optional list controls when the field should be shown.
   * If omitted, the field is always visible.
   */
  visibleForOperations?: string[];
}

export interface Tool {
  id: string;
  title: string;
  description: string;
  icon: string;
  accent: string;
  status: ToolStatus;
  category: ToolCategory;
  config?: ToolConfig;
  tag?: string;
}

// Category-based accent mapping
export const categoryAccents: Record<ToolCategory, string> = {
  pptx: "from-orange-500 to-red-500",
  organize: "from-purple-500 to-violet-600",
  convert: "from-blue-500 to-cyan-500",
  edit: "from-amber-500 to-orange-500",
  security: "from-rose-500 to-red-600",
  optimize: "from-emerald-500 to-green-600",
  ai: "from-violet-500 to-purple-600",
  extract: "from-teal-500 to-cyan-600",
};

export const tools: Tool[] = [
  // PPTX Tools
  {
    id: "merge-pptx",
    title: "Merge PPTX",
    description: "Combine multiple PPTX decks into one.",
    icon: "Layers",
    accent: "from-orange-500 to-red-500",
    tag: "Priority",
    status: "ready",
    category: "pptx",
    config: {
      endpoint: "/api/pptx/merge",
      method: "POST",
      acceptedFiles: [".pptx"],
      multiFile: true,
      minFiles: 2,
      outputFileName: "merged.pptx",
      outputMimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    },
  },
  // PDF Organize Tools
  {
    id: "merge-pdf",
    title: "Merge PDF",
    description: "Combine multiple PDFs into a single file.",
    icon: "FileStack",
    accent: "from-purple-500 to-violet-600",
    status: "ready",
    category: "organize",
    config: {
      endpoint: "/api/pdf/merge",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: true,
      minFiles: 2,
      outputFileName: "merged.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "split-pdf",
    title: "Split PDF",
    description: "Extract pages from a PDF.",
    icon: "Scissors",
    accent: "from-purple-500 to-violet-600",
    status: "ready",
    category: "organize",
    config: {
      endpoint: "/api/pdf/split",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "pages",
          label: "Pages to extract (e.g., 1, 3, 5)",
          type: "text",
          defaultValue: "1",
          placeholder: "1, 2, 3",
          required: true,
        },
      ],
      outputFileName: "split.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "compress-pdf",
    title: "Compress PDF",
    description: "Reduce file size efficiently.",
    icon: "FileDown",
    accent: "from-emerald-500 to-green-600",
    status: "ready",
    category: "optimize",
    config: {
      endpoint: "/api/pdf/compress",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "mode",
          label: "Compression Mode",
          type: "select",
          defaultValue: "smart",
          options: [
            { value: "smart", label: "Smart (compress images, keep text selectable)" },
            { value: "aggressive", label: "Aggressive (max compression, text becomes image)" },
          ],
        },
        {
          name: "compression_level",
          label: "Quality Level (1 = smallest file, 100 = best quality)",
          type: "range",
          defaultValue: 50,
          min: 1,
          max: 100,
          step: 1,
        },
      ],
      outputFileName: "compressed.pdf",
      outputMimeType: "application/pdf",
    },
  },
  // Conversions
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    description: "Convert PDF to editable Word doc.",
    icon: "FileText",
    accent: "from-blue-500 to-cyan-500",
    status: "ready",
    category: "convert",
    config: {
      endpoint: "/api/convert/pdf-to-word",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      outputFileName: "document.docx",
      outputMimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    },
  },
  {
    id: "pdf-to-ppt",
    title: "PDF to Powerpoint",
    description: "Convert PDF to editable slides.",
    icon: "Presentation",
    accent: "from-blue-500 to-cyan-500",
    status: "ready",
    category: "convert",
    config: {
      endpoint: "/api/convert/pdf-to-ppt",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "dpi",
          label: "Quality (DPI)",
          type: "select",
          defaultValue: "150",
          options: [
            { value: "72", label: "Fast (72 DPI)" },
            { value: "150", label: "Standard (150 DPI)" },
            { value: "300", label: "High Quality (300 DPI)" },
          ],
        },
      ],
      outputFileName: "presentation.pptx",
      outputMimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    },
  },
  {
    id: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Extract tables to Excel.",
    icon: "Sheet",
    accent: "from-blue-500 to-cyan-500",
    status: "ready",
    category: "convert",
    config: {
      endpoint: "/api/convert/pdf-to-excel",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      outputFileName: "spreadsheet.xlsx",
      outputMimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    },
  },
  {
    id: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert Word to PDF.",
    icon: "FileType",
    accent: "from-blue-500 to-cyan-500",
    status: "ready",
    category: "convert",
    config: {
      endpoint: "/api/convert/word-to-pdf",
      method: "POST",
      acceptedFiles: [".doc", ".docx"],
      multiFile: false,
      outputFileName: "document.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "ppt-to-pdf",
    title: "PPT to PDF",
    description: "Convert PowerPoint to PDF.",
    icon: "FileOutput",
    accent: "from-blue-500 to-cyan-500",
    status: "ready",
    category: "convert",
    config: {
      endpoint: "/api/convert/ppt-to-pdf",
      method: "POST",
      acceptedFiles: [".pptx"],
      multiFile: false,
      outputFileName: "presentation.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Convert Excel to PDF.",
    icon: "Table",
    accent: "from-blue-500 to-cyan-500",
    status: "ready",
    category: "convert",
    config: {
      endpoint: "/api/convert/excel-to-pdf",
      method: "POST",
      acceptedFiles: [".xls", ".xlsx"],
      multiFile: false,
      outputFileName: "spreadsheet.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "edit-pdf",
    title: "Edit PDF",
    description: "Add text, images, and shapes.",
    icon: "PenLine",
    accent: "from-amber-500 to-orange-500",
    tag: "New",
    status: "ready",
    category: "edit",
    config: {
      endpoint: "/api/pdf/edit/add-text",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "text",
          label: "Text to Add",
          type: "text",
          defaultValue: "",
          placeholder: "Enter text to add",
          required: true,
        },
        {
          name: "page",
          label: "Page Number",
          type: "number",
          defaultValue: 1,
          min: 1,
        },
        {
          name: "x",
          label: "X Position (from left)",
          type: "number",
          defaultValue: 100,
          min: 0,
        },
        {
          name: "y",
          label: "Y Position (from bottom)",
          type: "number",
          defaultValue: 700,
          min: 0,
        },
        {
          name: "font_size",
          label: "Font Size",
          type: "number",
          defaultValue: 14,
          min: 6,
          max: 72,
        },
        {
          name: "color",
          label: "Text Color",
          type: "select",
          defaultValue: "black",
          options: [
            { value: "black", label: "Black" },
            { value: "blue", label: "Blue" },
            { value: "red", label: "Red" },
            { value: "green", label: "Green" },
          ],
        },
      ],
      outputFileName: "edited.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "pdf-to-jpg",
    title: "PDF to Images",
    description: "Convert PDF to JPG, PNG, WEBP, TIFF, or BMP.",
    icon: "Image",
    accent: "from-blue-500 to-cyan-500",
    status: "ready",
    category: "convert",
    config: {
      endpoint: "/api/convert/pdf-to-images",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "format",
          label: "Image Format",
          type: "select",
          defaultValue: "jpg",
          options: [
            { value: "jpg", label: "JPG (smallest, lossy)" },
            { value: "png", label: "PNG (lossless, transparent)" },
            { value: "webp", label: "WEBP (modern, efficient)" },
            { value: "tiff", label: "TIFF (archival quality)" },
            { value: "bmp", label: "BMP (uncompressed)" },
          ],
        },
        {
          name: "dpi",
          label: "Quality (DPI)",
          type: "select",
          defaultValue: "150",
          options: [
            { value: "72", label: "Fast (72 DPI)" },
            { value: "150", label: "Standard (150 DPI)" },
            { value: "300", label: "High Quality (300 DPI)" },
          ],
        },
      ],
      outputFileName: "images.zip",
      outputMimeType: "application/zip",
    },
  },
  {
    id: "jpg-to-pdf",
    title: "JPG to PDF",
    description: "Convert images to PDF.",
    icon: "ImagePlus",
    accent: "from-blue-500 to-cyan-500",
    status: "ready",
    category: "convert",
    config: {
      endpoint: "/api/convert/jpg-to-pdf",
      method: "POST",
      acceptedFiles: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp"],
      multiFile: true,
      minFiles: 1,
      formFields: [
        {
          name: "page_size",
          label: "Page Size",
          type: "select",
          defaultValue: "a4",
          options: [
            { value: "a4", label: "A4" },
            { value: "letter", label: "Letter" },
            { value: "fit", label: "Fit to Image" },
          ],
        },
      ],
      outputFileName: "images.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "image-editor",
    title: "Image Editor",
    description: "Resize, rotate, blur, remove background, change format, and more.",
    icon: "Wand2",
    accent: "from-pink-500 to-rose-500",
    status: "ready",
    category: "edit",
    config: {
      endpoint: "/api/image/edit",
      method: "POST",
      acceptedFiles: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp", ".tiff", ".tif"],
      multiFile: false,
      formFields: [
        {
          name: "operation",
          label: "Select Operation",
          type: "select",
          defaultValue: "resize",
          options: [
            { value: "resize", label: "Resize" },
            { value: "rotate", label: "Rotate" },
            { value: "blur", label: "Blur" },
            { value: "grayscale", label: "Grayscale" },
            { value: "brightness", label: "Adjust Brightness" },
            { value: "contrast", label: "Adjust Contrast" },
            { value: "flip", label: "Flip" },
            { value: "remove_background", label: "Remove Background" },
            { value: "add_background", label: "Add Background Color" },
            { value: "format", label: "Change Format" },
          ],
        },
        {
          name: "percentage",
          label: "Resize Percentage (1-500%)",
          type: "number",
          defaultValue: 100,
          min: 1,
          max: 500,
          visibleForOperations: ["resize"],
        },
        {
          name: "angle",
          label: "Rotation Angle (degrees)",
          type: "number",
          defaultValue: 0,
          visibleForOperations: ["rotate"],
        },
        {
          name: "radius",
          label: "Blur Radius (pixels)",
          type: "number",
          defaultValue: 5,
          min: 1,
          max: 50,
          visibleForOperations: ["blur"],
        },
        {
          name: "factor",
          label: "Brightness/Contrast Factor (0.5-2.0)",
          type: "number",
          defaultValue: 1.0,
          min: 0.5,
          max: 2.0,
          step: 0.1,
          visibleForOperations: ["brightness", "contrast"],
        },
        {
          name: "direction",
          label: "Flip Direction",
          type: "select",
          defaultValue: "horizontal",
          options: [
            { value: "horizontal", label: "Flip Horizontally" },
            { value: "vertical", label: "Flip Vertically" },
          ],
          visibleForOperations: ["flip"],
        },
        {
          name: "bg_color",
          label: "Background Color (Hex: e.g., FFFFFF)",
          type: "text",
          defaultValue: "FFFFFF",
          placeholder: "FFFFFF",
          visibleForOperations: ["add_background"],
        },
        {
          name: "output_format",
          label: "Output Format",
          type: "select",
          defaultValue: "PNG",
          options: [
            { value: "PNG", label: "PNG (Lossless)" },
            { value: "JPG", label: "JPG (Compressed)" },
            { value: "WEBP", label: "WEBP (Modern)" },
            { value: "BMP", label: "BMP (Uncompressed)" },
            { value: "TIFF", label: "TIFF (Archival)" },
          ],
        },
      ],
      outputFileName: "edited_image.png",
      outputMimeType: "image/png",
    },
  },
  {
    id: "sign-pdf",
    title: "Sign PDF",
    description: "Add digital signatures.",
    icon: "PenTool",
    accent: "from-amber-500 to-orange-500",
    status: "ready",
    category: "edit",
    config: {
      endpoint: "/api/pdf/sign/text",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "name",
          label: "Your Name (Signature)",
          type: "text",
          defaultValue: "",
          placeholder: "Enter your name",
          required: true,
        },
        {
          name: "page",
          label: "Page Number (-1 for last page)",
          type: "number",
          defaultValue: -1,
        },
        {
          name: "x",
          label: "X Position (from left)",
          type: "number",
          defaultValue: 100,
          min: 0,
        },
        {
          name: "y",
          label: "Y Position (from bottom)",
          type: "number",
          defaultValue: 100,
          min: 0,
        },
        {
          name: "font_size",
          label: "Signature Size",
          type: "number",
          defaultValue: 24,
          min: 12,
          max: 72,
        },
        {
          name: "include_date",
          label: "Include Date",
          type: "checkbox",
          defaultValue: true,
        },
      ],
      outputFileName: "signed.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "watermark",
    title: "Watermark",
    description: "Stamp text over your PDF.",
    icon: "Droplet",
    accent: "from-amber-500 to-orange-500",
    status: "ready",
    category: "edit",
    config: {
      endpoint: "/api/pdf/watermark",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "text",
          label: "Watermark Text",
          type: "text",
          defaultValue: "CONFIDENTIAL",
          placeholder: "Enter watermark text",
          required: true,
        },
        {
          name: "opacity",
          label: "Opacity",
          type: "range",
          defaultValue: 0.3,
          min: 0.1,
          max: 1.0,
          step: 0.1,
        },
        {
          name: "angle",
          label: "Angle (degrees)",
          type: "number",
          defaultValue: 45,
          min: -180,
          max: 180,
        },
        {
          name: "font_size",
          label: "Font Size",
          type: "number",
          defaultValue: 60,
          min: 10,
          max: 200,
        },
      ],
      outputFileName: "watermarked.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "rotate-pdf",
    title: "Rotate PDF",
    description: "Rotate PDF pages.",
    icon: "RotateCw",
    accent: "from-purple-500 to-violet-600",
    status: "ready",
    category: "organize",
    config: {
      endpoint: "/api/pdf/rotate",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "angle",
          label: "Rotation Angle",
          type: "select",
          defaultValue: "90",
          options: [
            { value: "90", label: "90° Clockwise" },
            { value: "180", label: "180°" },
            { value: "270", label: "90° Counter-Clockwise" },
          ],
        },
        {
          name: "pages",
          label: "Pages (leave empty for all)",
          type: "text",
          defaultValue: "",
          placeholder: "1, 2, 5 (or empty for all)",
        },
      ],
      outputFileName: "rotated.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "html-to-pdf",
    title: "HTML to PDF",
    description: "Convert URL to PDF.",
    icon: "Globe",
    accent: "from-blue-500 to-cyan-500",
    status: "ready",
    category: "convert",
    config: {
      endpoint: "/api/convert/html-to-pdf",
      method: "POST",
      acceptedFiles: [],
      multiFile: false,
      formFields: [
        {
          name: "url",
          label: "Website URL",
          type: "text",
          defaultValue: "",
          placeholder: "https://example.com",
          required: true,
        },
      ],
      outputFileName: "webpage.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "unlock-pdf",
    title: "Unlock PDF",
    description: "Remove password security.",
    icon: "Unlock",
    accent: "from-rose-500 to-red-600",
    status: "ready",
    category: "security",
    config: {
      endpoint: "/api/pdf/unlock",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "password",
          label: "PDF Password",
          type: "text",
          defaultValue: "",
          placeholder: "Enter current password",
          required: true,
        },
      ],
      outputFileName: "unlocked.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "protect-pdf",
    title: "Protect PDF",
    description: "Encrypt with password.",
    icon: "Lock",
    accent: "from-rose-500 to-red-600",
    status: "ready",
    category: "security",
    config: {
      endpoint: "/api/pdf/protect",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "password",
          label: "Password",
          type: "text",
          defaultValue: "",
          placeholder: "Enter password",
          required: true,
        },
        {
          name: "allow_printing",
          label: "Allow Printing",
          type: "checkbox",
          defaultValue: true,
        },
        {
          name: "allow_copying",
          label: "Allow Copying Text",
          type: "checkbox",
          defaultValue: false,
        },
      ],
      outputFileName: "protected.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "organize-pdf",
    title: "Organize PDF",
    description: "Sort and reorder pages.",
    icon: "ListOrdered",
    accent: "from-purple-500 to-violet-600",
    status: "ready",
    category: "organize",
    config: {
      endpoint: "/api/pdf/organize",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "order",
          label: "New page order (e.g., 3, 1, 2, 4)",
          type: "text",
          defaultValue: "",
          placeholder: "3, 1, 2, 4",
          required: true,
        },
      ],
      outputFileName: "organized.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "repair-pdf",
    title: "Repair PDF",
    description: "Fix damaged PDFs.",
    icon: "Wrench",
    accent: "from-emerald-500 to-green-600",
    status: "ready",
    category: "optimize",
    config: {
      endpoint: "/api/pdf/repair",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      outputFileName: "repaired.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "page-numbers",
    title: "Page Numbers",
    description: "Add page numbering.",
    icon: "Hash",
    accent: "from-amber-500 to-orange-500",
    status: "ready",
    category: "edit",
    config: {
      endpoint: "/api/pdf/page-numbers",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "position",
          label: "Position",
          type: "select",
          defaultValue: "bottom-center",
          options: [
            { value: "bottom-center", label: "Bottom Center" },
            { value: "bottom-left", label: "Bottom Left" },
            { value: "bottom-right", label: "Bottom Right" },
            { value: "top-center", label: "Top Center" },
            { value: "top-left", label: "Top Left" },
            { value: "top-right", label: "Top Right" },
          ],
        },
        {
          name: "start_number",
          label: "Starting Number",
          type: "number",
          defaultValue: 1,
          min: 1,
        },
        {
          name: "font_size",
          label: "Font Size",
          type: "number",
          defaultValue: 12,
          min: 6,
          max: 72,
        },
      ],
      outputFileName: "numbered.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "ocr-pdf",
    title: "OCR PDF",
    description: "Make PDFs searchable.",
    icon: "ScanText",
    accent: "from-amber-500 to-orange-500",
    status: "ready",
    category: "edit",
    config: {
      endpoint: "/api/ocr/make-searchable",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "language",
          label: "Language",
          type: "select",
          defaultValue: "eng",
          options: [
            { value: "eng", label: "English" },
            { value: "fra", label: "French" },
            { value: "deu", label: "German" },
            { value: "spa", label: "Spanish" },
            { value: "ita", label: "Italian" },
            { value: "por", label: "Portuguese" },
            { value: "chi_sim", label: "Chinese (Simplified)" },
            { value: "jpn", label: "Japanese" },
            { value: "ara", label: "Arabic" },
          ],
        },
      ],
      outputFileName: "searchable.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "crop-pdf",
    title: "Crop PDF",
    description: "Crop PDF margins.",
    icon: "Crop",
    accent: "from-amber-500 to-orange-500",
    tag: "New",
    status: "ready",
    category: "edit",
    config: {
      endpoint: "/api/pdf/crop",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "left",
          label: "Left margin (pt)",
          type: "number",
          defaultValue: 0,
          min: 0,
        },
        {
          name: "right",
          label: "Right margin (pt)",
          type: "number",
          defaultValue: 0,
          min: 0,
        },
        {
          name: "top",
          label: "Top margin (pt)",
          type: "number",
          defaultValue: 0,
          min: 0,
        },
        {
          name: "bottom",
          label: "Bottom margin (pt)",
          type: "number",
          defaultValue: 0,
          min: 0,
        },
      ],
      outputFileName: "cropped.pdf",
      outputMimeType: "application/pdf",
    },
  },
  
  // ============ AI-POWERED TOOLS ============
  {
    id: "ai-summarize",
    title: "AI Summarize PDF",
    description: "Get AI-generated summary and key points from any PDF.",
    icon: "Sparkles",
    accent: "from-violet-500 to-purple-600",
    tag: "AI",
    status: "ready",
    category: "ai",
    config: {
      endpoint: "/api/ai/summarize",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "length",
          label: "Summary Length",
          type: "select",
          defaultValue: "medium",
          options: [
            { value: "brief", label: "Brief (1-2 paragraphs)" },
            { value: "medium", label: "Medium (3-5 paragraphs)" },
            { value: "detailed", label: "Detailed (full analysis)" },
          ],
        },
        {
          name: "style",
          label: "Output Style",
          type: "select",
          defaultValue: "bullets",
          options: [
            { value: "bullets", label: "Bullet Points" },
            { value: "prose", label: "Prose" },
            { value: "outline", label: "Outline" },
          ],
        },
      ],
      outputFileName: "summary.txt",
      outputMimeType: "text/plain",
    },
  },
  {
    id: "ai-chat-pdf",
    title: "Chat with PDF",
    description: "Ask questions and get answers from your document using AI.",
    icon: "MessageSquareText",
    accent: "from-violet-500 to-purple-600",
    tag: "AI",
    status: "ready",
    category: "ai",
    config: {
      endpoint: "/api/ai/chat",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "question",
          label: "Your Question",
          type: "text",
          defaultValue: "",
          placeholder: "What is this document about?",
          required: true,
        },
      ],
      outputFileName: "answer.txt",
      outputMimeType: "text/plain",
    },
  },
  {
    id: "ai-translate",
    title: "AI Translate PDF",
    description: "Translate your PDF to another language using AI.",
    icon: "Languages",
    accent: "from-violet-500 to-purple-600",
    tag: "AI",
    status: "ready",
    category: "ai",
    config: {
      endpoint: "/api/ai/translate",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "target_language",
          label: "Target Language",
          type: "select",
          defaultValue: "es",
          options: [
            { value: "bn", label: "Bangla (Bengali)" },
            { value: "es", label: "Spanish" },
            { value: "fr", label: "French" },
            { value: "de", label: "German" },
            { value: "it", label: "Italian" },
            { value: "pt", label: "Portuguese" },
            { value: "zh", label: "Chinese" },
            { value: "ja", label: "Japanese" },
            { value: "ko", label: "Korean" },
            { value: "ar", label: "Arabic" },
            { value: "hi", label: "Hindi" },
            { value: "ru", label: "Russian" },
            { value: "tr", label: "Turkish" },
            { value: "vi", label: "Vietnamese" },
            { value: "th", label: "Thai" },
          ],
        },
      ],
      outputFileName: "translated.pdf",
      outputMimeType: "application/pdf",
    },
  },
  
  // ============ EXTRACTION TOOLS ============
  {
    id: "extract-text",
    title: "Extract Text",
    description: "Pull all text content from PDF as plain text or Markdown.",
    icon: "FileText",
    accent: "from-teal-500 to-cyan-600",
    status: "ready",
    category: "extract",
    config: {
      endpoint: "/api/extract/text",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "format",
          label: "Output Format",
          type: "select",
          defaultValue: "txt",
          options: [
            { value: "txt", label: "Plain Text (.txt)" },
            { value: "md", label: "Markdown (.md)" },
            { value: "html", label: "HTML (.html)" },
          ],
        },
        {
          name: "preserve_layout",
          label: "Preserve Layout",
          type: "checkbox",
          defaultValue: false,
        },
      ],
      outputFileName: "extracted.txt",
      outputMimeType: "text/plain",
    },
  },
  {
    id: "extract-images",
    title: "Extract Images",
    description: "Export all images embedded in a PDF document.",
    icon: "Images",
    accent: "from-teal-500 to-cyan-600",
    status: "ready",
    category: "extract",
    config: {
      endpoint: "/api/extract/images",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "format",
          label: "Image Format",
          type: "select",
          defaultValue: "png",
          options: [
            { value: "png", label: "PNG (lossless)" },
            { value: "jpg", label: "JPEG (smaller)" },
            { value: "webp", label: "WebP (modern)" },
          ],
        },
        {
          name: "min_size",
          label: "Min Image Size (px)",
          type: "number",
          defaultValue: 50,
          min: 1,
          max: 1000,
        },
      ],
      outputFileName: "images.zip",
      outputMimeType: "application/zip",
    },
  },
  {
    id: "extract-tables",
    title: "Extract Tables",
    description: "Extract tables from PDF to CSV or Excel format.",
    icon: "Table2",
    accent: "from-teal-500 to-cyan-600",
    status: "ready",
    category: "extract",
    config: {
      endpoint: "/api/extract/tables",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "format",
          label: "Output Format",
          type: "select",
          defaultValue: "csv",
          options: [
            { value: "csv", label: "CSV" },
            { value: "xlsx", label: "Excel (.xlsx)" },
            { value: "json", label: "JSON" },
          ],
        },
        {
          name: "pages",
          label: "Pages (empty = all)",
          type: "text",
          defaultValue: "",
          placeholder: "1, 2, 5-10",
        },
      ],
      outputFileName: "tables.zip",
      outputMimeType: "application/zip",
    },
  },
  {
    id: "extract-metadata",
    title: "Extract Metadata",
    description: "View document properties, author, dates, and hidden data.",
    icon: "Info",
    accent: "from-teal-500 to-cyan-600",
    status: "ready",
    category: "extract",
    config: {
      endpoint: "/api/extract/metadata",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      outputFileName: "metadata.json",
      outputMimeType: "application/json",
    },
  },
  
  // ============ ADVANCED TOOLS ============
  {
    id: "compare-pdf",
    title: "Compare PDFs",
    description: "Compare two PDFs and highlight differences.",
    icon: "GitCompare",
    accent: "from-indigo-500 to-blue-600",
    tag: "New",
    status: "ready",
    category: "edit",
    config: {
      endpoint: "/api/pdf/compare",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: true,
      minFiles: 2,
      formFields: [
        {
          name: "mode",
          label: "Comparison Mode",
          type: "select",
          defaultValue: "visual",
          options: [
            { value: "visual", label: "Visual (overlay)" },
            { value: "text", label: "Text differences" },
            { value: "both", label: "Both" },
          ],
        },
      ],
      outputFileName: "comparison.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "redact-pdf",
    title: "Redact PDF",
    description: "Permanently black out sensitive information.",
    icon: "EyeOff",
    accent: "from-rose-500 to-red-600",
    status: "ready",
    category: "security",
    config: {
      endpoint: "/api/pdf/redact",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "patterns",
          label: "Patterns to redact (regex, comma-separated)",
          type: "text",
          defaultValue: "",
          placeholder: "email, phone, SSN",
        },
        {
          name: "redact_emails",
          label: "Auto-redact Emails",
          type: "checkbox",
          defaultValue: true,
        },
        {
          name: "redact_phones",
          label: "Auto-redact Phone Numbers",
          type: "checkbox",
          defaultValue: true,
        },
        {
          name: "redact_ssn",
          label: "Auto-redact SSN/ID Numbers",
          type: "checkbox",
          defaultValue: true,
        },
      ],
      outputFileName: "redacted.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "flatten-pdf",
    title: "Flatten PDF",
    description: "Remove form fields, annotations, and interactivity.",
    icon: "Layers2",
    accent: "from-emerald-500 to-green-600",
    status: "ready",
    category: "optimize",
    config: {
      endpoint: "/api/pdf/flatten",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "flatten_forms",
          label: "Flatten Form Fields",
          type: "checkbox",
          defaultValue: true,
        },
        {
          name: "flatten_annotations",
          label: "Flatten Annotations",
          type: "checkbox",
          defaultValue: true,
        },
      ],
      outputFileName: "flattened.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "pdf-to-markdown",
    title: "PDF to Markdown",
    description: "Convert PDF to clean Markdown with formatting preserved.",
    icon: "FileCode",
    accent: "from-blue-500 to-cyan-500",
    status: "ready",
    category: "convert",
    config: {
      endpoint: "/api/convert/pdf-to-markdown",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "include_images",
          label: "Include Images (base64)",
          type: "checkbox",
          defaultValue: false,
        },
        {
          name: "preserve_tables",
          label: "Preserve Tables",
          type: "checkbox",
          defaultValue: true,
        },
      ],
      outputFileName: "document.md",
      outputMimeType: "text/markdown",
    },
  },
  {
    id: "remove-pages",
    title: "Remove Pages",
    description: "Delete specific pages from a PDF.",
    icon: "FileX",
    accent: "from-purple-500 to-violet-600",
    status: "ready",
    category: "organize",
    config: {
      endpoint: "/api/pdf/remove-pages",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "pages",
          label: "Pages to remove (e.g., 1, 3, 5-7)",
          type: "text",
          defaultValue: "",
          placeholder: "1, 3, 5-7",
          required: true,
        },
      ],
      outputFileName: "trimmed.pdf",
      outputMimeType: "application/pdf",
    },
  },
  {
    id: "add-bookmarks",
    title: "Add Bookmarks",
    description: "Create table of contents and navigation bookmarks.",
    icon: "Bookmark",
    accent: "from-amber-500 to-orange-500",
    status: "ready",
    category: "edit",
    config: {
      endpoint: "/api/pdf/add-bookmarks",
      method: "POST",
      acceptedFiles: [".pdf"],
      multiFile: false,
      formFields: [
        {
          name: "auto_detect",
          label: "Auto-detect headings",
          type: "checkbox",
          defaultValue: true,
        },
        {
          name: "bookmarks",
          label: "Manual bookmarks (page:title, one per line)",
          type: "text",
          defaultValue: "",
          placeholder: "1:Introduction\\n5:Chapter 1",
        },
      ],
      outputFileName: "bookmarked.pdf",
      outputMimeType: "application/pdf",
    },
  },
];
